### ISSUE TITLE
Considering renaming to react-native-wgpu?

### ISSUE THREAD

**Issue by wcandillon** [seanhenry/react-native-webgpu#1]
Hello Sean 👋🏻

I'm developing a WebGPU binding for React Native (we showed some demos of it at appjs last month: https://youtu.be/Pu-Zngp0JUU?si=fWPeBYSlUUFQo35n&t=890). Our implementation is based on Dawn and it looks like you are targeting WGPU.
On our side we might consider renaming to `react-native-wgpu` but this might be confusing since you are the project using WGPU. Let me know if you have any thoughts on this.

**Comment by seanhenry** [comment]
Hi William,

I'm actually targeting [webgpu-headers](https://github.com/webgpu-native/webgpu-headers) which means I should be able to link to Dawn or wgpu using the same api. But you're right, currently linking to wgpu as I've worked with it quite a lot in the past. I'm sorry that we're treading on each other's toes with regards to the name, but I'd like to keep `react-native-webgpu`.  

It's good to hear that you're working with webgpu (great demo!) and I'm excited to see what you do with it.

**Comment by wcandillon** [comment]
No problem about the name, I just wanted to check.
We had the same issue with RN Skia, where `react-native-skia` was taken when we wanted to publish the package.
These usually turn out not to be big issues.

You're making a very good point that we can link both WGPU and Dawn (hopefully) interchangeably.
In our case, the focus is on Dawn because we also want to use it as a backend for Skia.

We're having tons of fun with this project, and I bet you are too, so I'm completely happy to continue with the current setup.
If you think there is maybe a way to join forces or at least discuss how this could look, please reach out privately.
But again, I completely understand if not.

Right now, we have a really fun way to generate the bindings from their TypeScript definition (@types/webgpu). We run our e2e test suite against Chrome for reference and then against iOS and Android. I'd love to give you a sneak peek, but again, this should be open-source soon enough anyway.
